### ISSUE TITLE
Faulty sources for borders and for low-zoom residential areas

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/openmaptiles#10]
The simplification creates abstract forms which are hard to recognize.
![image](https://user-images.githubusercontent.com/689201/52866187-d86cee00-3146-11e9-9494-5d9e032e177e.png)

**Comment by zstadler** [comment]
- As you know, borders and residential are separate layers
- Please be specific about zoom levels
- In low zoom levels, the data is not taken from OSM
    - This may change for residential areas given https://github.com/IsraelHikingMap/openmaptiles/issues/6
- Border issues are hard to see when using dots...

**Comment by valleyofdawn** [comment]
It may indeed have nothing to do with simplification at low zoom levels but with the source of the data.
Basically both non-OSM sources are inadequate. The low-zoom urban areas are imaginary - based on some faulty automatic remote-sensing algorithm. The borders unnecessarily show territorial waters and what used to be the border along the Jordan River in 1917.

**Comment by zstadler** [comment]
Closing as duplicate

- Populated places are handled in #6 
- Borders are handled in #9
