### ISSUE TITLE
Show Hebrew name when there is no name:he

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/openmaptiles#18]
Some elements have Hebrew `name` values, but no `name:he` tags. In such cases, the `name_he` field is taken from the `name:en` tag, if exists, before using the `name` tag.

It would be better to check if the `name` value contains Hebrew letters before checking the existence of the `name:en` tag. Since such operation could be compute-intensive, consider performing it once per element rather than in each zoom level.

**Comment by HarelM** [comment]
So the logic is `name:he` then `name:en` then `name`? and this for the cases when `name` is in Arabic, right?

**Comment by zstadler** [comment]
yes

**Comment by zstadler** [comment]
Duplicate of https://github.com/IsraelHikingMap/VectorMap/issues/21
