### ISSUE TITLE
Add hill shading

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/openmaptiles#8]

**Comment by valleyofdawn** [comment]
Can be closed

**Comment by zstadler** [comment]
The TerrainRGB tiles were manually created from the DEM and placed in a separate mbtiles file. The TerrainRGB tiles are available as a separate source provided by the same vector-tiles server using the following `data` configuration segment:

```json
  "data": {
    "v3": {
      "mbtiles": "tiles.mbtiles"
    },
    "TerrainRGB": {
      "mbtiles": "Israel_TerrainRGB.mbtiles"
    }
  }
```
