### ISSUE TITLE
International border with Jordan outdated

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/openmaptiles#9]
It should be taken from OSM where I updated it a year or two ago.
The border passes by definition along the Jordan river, not where it appears now.

**Comment by zstadler** [comment]
Please give an example, including its location and the zoom level

**Comment by valleyofdawn** [comment]
http://31.154.215.180:8088/#13.59/31.93342/35.5548

**Comment by zstadler** [comment]
![image](https://user-images.githubusercontent.com/1304610/52868068-07855e80-314b-11e9-9344-daabf3aa7437.png)

**Comment by zstadler** [comment]
The OSM borders used by OpenMapTiles were [generated from the OSM planet file 2017-11-20.pbf](https://github.com/openmaptiles/import-osmborder/releases/tag/v0.4)

The International border with Jordan was updated on 2018-02-11.

**Comment by zstadler** [comment]
A new release was requested in https://github.com/openmaptiles/import-osmborder/issues/5

**Comment by zstadler** [comment]
Resolved by 109fcb97022e0358b7f4924509c887f056f715e6
